trigger:
  batch: true

pool:
  vmImage: 'VS2017-Win2016'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: '**/**/*.csproj'

- task: NuGetToolInstaller@0

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/StrainTest/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: NuGetCommand@2
  inputs:
    command: pack
    configurationToPack: Release
    searchPatternPack: '**/TangleChainIXI/*.csproj'
