trigger:
  batch: true

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '**/**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/StrainTest/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
