trigger:
  batch: true

pool:
  vmImage: 'VS2017-Win2016'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: build
    configurationToPack: Release
    projects: '**/**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/StrainTest/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

