trigger:
  batch: true

pool:
  vmImage: 'VS2017-Win2016'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: build
    arguments: '--configuration $(BuildConfiguration)'
    projects: '**/**/*.csproj'

- task: CopyFiles@2
  inputs:
    contents: '**/TangleChainIXI/**'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: CopyFiles@2
  inputs:
    contents: '**/Strain/**'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    ArtifactName: 'drop'
